// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_Project_API_02.Models;

#nullable disable

namespace Test_Project_API_02.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215234423_AddPriceImageToFavorites")]
    partial class AddPriceImageToFavorites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Test_Project_API_02.Models.Cart", b =>
                {
                    b.Property<int>("IdCart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Cart");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCart"));

                    b.Property<int?>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("Id_User");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Total_Price");

                    b.Property<int>("TotalProducts")
                        .HasColumnType("int")
                        .HasColumnName("Total_Products");

                    b.HasKey("IdCart");

                    b.HasIndex("IdUser");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("Test_Project_API_02.Models.CartItem", b =>
                {
                    b.Property<int>("IdCartItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Cart_Item");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCartItem"));

                    b.Property<int?>("IdCart")
                        .HasColumnType("int")
                        .HasColumnName("Id_Cart");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Image_Url");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Price");

                    b.Property<string>("ProductApiName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Product_API_Name");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.HasKey("IdCartItem");

                    b.HasIndex("IdCart");

                    b.ToTable("Cart_Items", (string)null);
                });

            modelBuilder.Entity("Test_Project_API_02.Models.Favorite", b =>
                {
                    b.Property<int>("IdFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Favorite");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFavorite"));

                    b.Property<int?>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("Id_User");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductApiName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Product_API_Name");

                    b.HasKey("IdFavorite");

                    b.HasIndex("IdUser");

                    b.ToTable("Favorite", (string)null);
                });

            modelBuilder.Entity("Test_Project_API_02.Models.MedicineAvailability", b =>
                {
                    b.Property<int>("IdRequest")
                        .HasColumnType("int")
                        .HasColumnName("Id_Request");

                    b.Property<int>("IdUserPh")
                        .HasColumnType("int")
                        .HasColumnName("Id_User_PH");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int")
                        .HasColumnName("Available_Quantity");

                    b.HasKey("IdRequest", "IdUserPh");

                    b.HasIndex("IdUserPh");

                    b.ToTable("Medicine_Availability", (string)null);
                });

            modelBuilder.Entity("Test_Project_API_02.Models.MedicineRequest", b =>
                {
                    b.Property<int>("IdRequest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Request");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRequest"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasColumnName("Create_At")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("Id_User");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Medicine_Name");

                    b.Property<string>("OrderStatus")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("Order_Status")
                        .IsFixedLength();

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRequest");

                    b.HasIndex("IdUser");

                    b.ToTable("Medicine_Requests", (string)null);
                });

            modelBuilder.Entity("Test_Project_API_02.Models.Notification", b =>
                {
                    b.Property<int>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Notification");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotification"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasColumnName("Create_At")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("IdRequest")
                        .HasColumnType("int")
                        .HasColumnName("Id_Request");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("Id_User");

                    b.HasKey("IdNotification");

                    b.HasIndex("IdRequest");

                    b.HasIndex("IdUser");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Test_Project_API_02.Models.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Order");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrder"));

                    b.Property<DateTime>("CreateAtOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasColumnName("Create_At_Order")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("IdCart")
                        .HasColumnType("int")
                        .HasColumnName("Id_Cart");

                    b.Property<int?>("IdPaymentMethod")
                        .HasColumnType("int")
                        .HasColumnName("Id_Payment_Method");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("Id_User");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Total_Amount");

                    b.HasKey("IdOrder");

                    b.HasIndex("IdCart");

                    b.HasIndex("IdPaymentMethod");

                    b.HasIndex("IdUser");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Test_Project_API_02.Models.PaymentMethod", b =>
                {
                    b.Property<int>("IdPaymentMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Payment_Method");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaymentMethod"));

                    b.Property<string>("PaymentMethodType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("Payment_Method_Type")
                        .IsFixedLength();

                    b.HasKey("IdPaymentMethod");

                    b.ToTable("Payment_Methods", (string)null);
                });

            modelBuilder.Entity("Test_Project_API_02.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_User");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("BlockStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("Block_Status");

                    b.Property<string>("BloodType")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("Blood_Type");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasColumnName("Create_At")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_Of_Birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("First_Name");

                    b.Property<string>("Gender")
                        .HasColumnType("char(1)");

                    b.Property<string>("HealthStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Health_Status");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Last_Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Test_Project_API_02.Models.UsersAddress", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("Id_User");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdUser", "Address");

                    b.ToTable("Users_Addresses", (string)null);
                });

            modelBuilder.Entity("Test_Project_API_02.Models.UsersAllergy", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("Id_User");

                    b.Property<string>("Allergies")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUser", "Allergies");

                    b.ToTable("Users_Allergies", (string)null);
                });

            modelBuilder.Entity("Test_Project_API_02.Models.UsersChronicDisease", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("Id_User");

                    b.Property<string>("ChronicDiseaseName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Chronic_Disease_Name");

                    b.Property<string>("DiseaseType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Disease_Type");

                    b.HasKey("IdUser", "ChronicDiseaseName");

                    b.ToTable("Users_Chronic_Diseases", (string)null);
                });

            modelBuilder.Entity("Test_Project_API_02.Models.UsersPhone", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("Id_User");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdUser", "Phone");

                    b.ToTable("Users_Phones", (string)null);
                });

            modelBuilder.Entity("Test_Project_API_02.Models.Cart", b =>
                {
                    b.HasOne("Test_Project_API_02.Models.User", "IdUserNavigation")
                        .WithMany("Carts")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Test_Project_API_02.Models.CartItem", b =>
                {
                    b.HasOne("Test_Project_API_02.Models.Cart", "IdCartNavigation")
                        .WithMany("CartItems")
                        .HasForeignKey("IdCart")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IdCartNavigation");
                });

            modelBuilder.Entity("Test_Project_API_02.Models.Favorite", b =>
                {
                    b.HasOne("Test_Project_API_02.Models.User", "IdUserNavigation")
                        .WithMany("Favorites")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Test_Project_API_02.Models.MedicineAvailability", b =>
                {
                    b.HasOne("Test_Project_API_02.Models.MedicineRequest", "IdRequestNavigation")
                        .WithMany("MedicineAvailabilities")
                        .HasForeignKey("IdRequest")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Test_Project_API_02.Models.User", "IdUserPhNavigation")
                        .WithMany()
                        .HasForeignKey("IdUserPh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdRequestNavigation");

                    b.Navigation("IdUserPhNavigation");
                });

            modelBuilder.Entity("Test_Project_API_02.Models.MedicineRequest", b =>
                {
                    b.HasOne("Test_Project_API_02.Models.User", "IdUserNavigation")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Test_Project_API_02.Models.Notification", b =>
                {
                    b.HasOne("Test_Project_API_02.Models.MedicineRequest", "IdRequestNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("IdRequest")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Test_Project_API_02.Models.User", "IdUserNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IdRequestNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Test_Project_API_02.Models.Order", b =>
                {
                    b.HasOne("Test_Project_API_02.Models.Cart", "IdCartNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("IdCart")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Test_Project_API_02.Models.PaymentMethod", "IdPaymentMethodNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("IdPaymentMethod")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Test_Project_API_02.Models.User", "IdUserNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IdCartNavigation");

                    b.Navigation("IdPaymentMethodNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Test_Project_API_02.Models.UsersAddress", b =>
                {
                    b.HasOne("Test_Project_API_02.Models.User", "IdUserNavigation")
                        .WithMany("UsersAddresses")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Test_Project_API_02.Models.UsersAllergy", b =>
                {
                    b.HasOne("Test_Project_API_02.Models.User", "IdUserNavigation")
                        .WithMany("UsersAllergies")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Test_Project_API_02.Models.UsersChronicDisease", b =>
                {
                    b.HasOne("Test_Project_API_02.Models.User", "IdUserNavigation")
                        .WithMany("UsersChronicDiseases")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Test_Project_API_02.Models.UsersPhone", b =>
                {
                    b.HasOne("Test_Project_API_02.Models.User", "IdUserNavigation")
                        .WithMany("UsersPhones")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Test_Project_API_02.Models.Cart", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Test_Project_API_02.Models.MedicineRequest", b =>
                {
                    b.Navigation("MedicineAvailabilities");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Test_Project_API_02.Models.PaymentMethod", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Test_Project_API_02.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Favorites");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("UsersAddresses");

                    b.Navigation("UsersAllergies");

                    b.Navigation("UsersChronicDiseases");

                    b.Navigation("UsersPhones");
                });
#pragma warning restore 612, 618
        }
    }
}
